
services:

  drupal:
    image: drupal
    ports:
    - "8080:80"
    volumes:
    - ./drupal/modules:/var/www/html/modules
    - ./drupal/profiles:/var/www/html/profiles
    - ./drupal/themes:/var/www/html/themes
    - ./drupal/sites:/var/www/html/sites
    # - /var/www/html/modules
    # - /var/www/html/profiles
    # - /var/www/html/themes
    # - /var/www/html/sites
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
      MARIADB_ROOT_PASSWORD: test
    volumes:
      - ./mariadb/data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

# Needed for IT-Landscape but not required for Drupal
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://root:test@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
