name: TEST

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

# https://docs.docker.com/build/ci/github-actions/

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # https://github.com/marketplace/actions/docker-setup-compose
            - name: Docker Setup Compose
              # You may pin to the exact commit or the version.
              # uses: docker/setup-compose-action@364cc21a5de5b1ee4a7f5f9d3fa374ce0ccde746
              uses: docker/setup-compose-action@v1.2.0
            #   with:
            # Compose version. (eg. v2.32.4)
            # version:
            # Cache compose binary to GitHub Actions cache backend
            # cache-binary: true

            - name: Start Drupal containers
              run: docker compose up -d

            - name: health-check-for-website
              uses: Mustafakhn/health-check-action@v2
              with:
                  # the url of the website that you want to check
                  website_url: http://localhost:8080
                  # a version specific tagthat you want to search for in the given website
                  #   version_name: # optional, default is none
                  # the method that you want to use ( wget or curl ) default is curl
                  #   method: # optional, default is curl
                  # the time ( in seconds ) you want to run this action to try to reach the given website ( default is 300 )
                  timeout: 5000 # optional, default is 300
                  # how to tag the image Default: latest
                  #   tag: # optional

            - name: Stop Drupal containers
              run: docker compose down
